language: node_js

node_js:
  - "5"

# Speeds up build time since it doesn't have to install the same packages again.
cache:
  directories:
    - node_modules
    - $(npm config get prefix)/lib/node_modules
    - $(npm config get prefix)/bin/webpack
    - $(npm config get prefix)/bin/gulp
    - $(npm config get prefix)/bin/karma

before_script:
  - npm i -g webpack gulp karma

after_success:
  - npm run coveralls
