language: node_js

node_js:
  - "5"

# Speeds up build time since it doesn't have to install the same packages again.
cache:
  directories:
    - node_modules

before_script:
  - npm i -g webpack gulp karma

after_success:
  - npm run coveralls
